### ISSUE TITLE
Update to 1.19 and beyond? 

### ISSUE THREAD

**Issue by astridos2go** [ChloeDawn/Frameless#2]
Hi, I really enjoy using this mod. I used it on a Fabric Vanilla server I ran (meant for people to be able to join with vanilla clients), but I recently updated it to 1.19. Was just reaching out to see if this mod will be updated to the newer versions! Thanks!

**Comment by ChloeDawn** [comment]
The mod should work on 1.19, have you tested it? If it works, I'll update the supported version range on Modrinth!

**Comment by astridos2go** [comment]
I believe I tried it, but it complained when I tried to launch because it was expecting Minecraft 1.18.2. I don't exactly remember though, so I'll try again when I get home from work!

**Comment by ChloeDawn** [comment]
I've tested it myself and it works, so I've marked the mod as supporting 1.19 on Modrinth :)
